//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraditionGame.Utilities.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraditionGame.Utilities.Messages.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exists.
        /// </summary>
        public static string AccountExist {
            get {
                return ResourceManager.GetString("AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account registered with facebook does not exist.
        /// </summary>
        public static string AccountFBNotExist {
            get {
                return ResourceManager.GetString("AccountFBNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSafe has been linked to another account.
        /// </summary>
        public static string AccountLinkedSafeOtp {
            get {
                return ResourceManager.GetString("AccountLinkedSafeOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked.
        /// </summary>
        public static string AccountLock {
            get {
                return ResourceManager.GetString("AccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account logged in too many times allowed.
        /// </summary>
        public static string AccountLoginOvertime {
            get {
                return ResourceManager.GetString("AccountLoginOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is not an account registered with facebook.
        /// </summary>
        public static string AccountNotFB {
            get {
                return ResourceManager.GetString("AccountNotFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number does not exist in the AppSafe system.
        /// </summary>
        public static string AccountNotLinkSafe {
            get {
                return ResourceManager.GetString("AccountNotLinkSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receiving account does not exist.
        /// </summary>
        public static string AccountReceiveNotExist {
            get {
                return ResourceManager.GetString("AccountReceiveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is Invalid. Thank you for using the service.
        /// </summary>
        public static string AccountSafeInValid {
            get {
                return ResourceManager.GetString("AccountSafeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is not configured with the game system. Thank you for using the service.
        /// </summary>
        public static string AccountSaveNotLink {
            get {
                return ResourceManager.GetString("AccountSaveNotLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated username and password.
        /// </summary>
        public static string AccountUpdateFBOneTime {
            get {
                return ResourceManager.GetString("AccountUpdateFBOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not configured to send otp.
        /// </summary>
        public static string AcountNotConfigOtp {
            get {
                return ResourceManager.GetString("AcountNotConfigOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift exchange failed.
        /// </summary>
        public static string AdBoxFail {
            get {
                return ResourceManager.GetString("AdBoxFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid redemption type.
        /// </summary>
        public static string AdBoxGiftCodeInValid {
            get {
                return ResourceManager.GetString("AdBoxGiftCodeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful gift exchange.
        /// </summary>
        public static string AdBoxSuccess {
            get {
                return ResourceManager.GetString("AdBoxSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent code already in use.
        /// </summary>
        public static string AgencyCodeInUse {
            get {
                return ResourceManager.GetString("AgencyCodeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent has been locked.
        /// </summary>
        public static string AgencyDisable {
            get {
                return ResourceManager.GetString("AgencyDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent already exists.
        /// </summary>
        public static string AgencyExist {
            get {
                return ResourceManager.GetString("AgencyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The facebook link is already in use.
        /// </summary>
        public static string AgencyFBLinkInUse {
            get {
                return ResourceManager.GetString("AgencyFBLinkInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent has been locked.
        /// </summary>
        public static string AgencyLock {
            get {
                return ResourceManager.GetString("AgencyLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent does not exist.
        /// </summary>
        public static string AgencyNotExist {
            get {
                return ResourceManager.GetString("AgencyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent security code has been used.
        /// </summary>
        public static string AgencySecretInUse {
            get {
                return ResourceManager.GetString("AgencySecretInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount required to enter.
        /// </summary>
        public static string AmountInValid {
            get {
                return ResourceManager.GetString("AmountInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account does not have enough money to change the card.
        /// </summary>
        public static string AmountNotEnoghToCardExchange {
            get {
                return ResourceManager.GetString("AmountNotEnoghToCardExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The safe vault does not have enough money to withdraw.
        /// </summary>
        public static string AmountNotEnoughToOpenSafe {
            get {
                return ResourceManager.GetString("AmountNotEnoughToOpenSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account does not have enough money to transfer to the safe vault.
        /// </summary>
        public static string AmountNotEnoughToSafe {
            get {
                return ResourceManager.GetString("AmountNotEnoughToSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount.
        /// </summary>
        public static string AmountNotValid {
            get {
                return ResourceManager.GetString("AmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account does not have enough funds to make the transaction.
        /// </summary>
        public static string AmountNotValidToTranferBit {
            get {
                return ResourceManager.GetString("AmountNotValidToTranferBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is maintaining this function. Please come back later.
        /// </summary>
        public static string AnphaMsg {
            get {
                return ResourceManager.GetString("AnphaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are enabling login security. To do this you need to disable login security.
        /// </summary>
        public static string AuthenTypeNeedRemove {
            get {
                return ResourceManager.GetString("AuthenTypeNeedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid avatar.
        /// </summary>
        public static string AvatarIncorrect {
            get {
                return ResourceManager.GetString("AvatarIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update avatar successfully.
        /// </summary>
        public static string AvatarUpdateSuccess {
            get {
                return ResourceManager.GetString("AvatarUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is not enough to make a transaction.
        /// </summary>
        public static string BalanceNotEnough {
            get {
                return ResourceManager.GetString("BalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer amount must be the value : {0}.
        /// </summary>
        public static string BetweenAmountTranfer {
            get {
                return ResourceManager.GetString("BetweenAmountTranfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth.
        /// </summary>
        public static string BirthdayIncorrect {
            get {
                return ResourceManager.GetString("BirthdayIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive success milestones.
        /// </summary>
        public static string Bom1AddSuccess {
            get {
                return ResourceManager.GetString("Bom1AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get reward for failure.
        /// </summary>
        public static string Bom1AdFail {
            get {
                return ResourceManager.GetString("Bom1AdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit for receiving milestone rewards has expired.
        /// </summary>
        public static string Bom1OverQuata {
            get {
                return ResourceManager.GetString("Bom1OverQuata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has received a milestone reward.
        /// </summary>
        public static string Bom1UserReceived {
            get {
                return ResourceManager.GetString("Bom1UserReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift code campaign does not exist.
        /// </summary>
        public static string CampaignNotExist {
            get {
                return ResourceManager.GetString("CampaignNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The campaign fund has run out.
        /// </summary>
        public static string CampaignOutMoney {
            get {
                return ResourceManager.GetString("CampaignOutMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code cannot be empty.
        /// </summary>
        public static string CapchaRequired {
            get {
                return ResourceManager.GetString("CapchaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System busy.
        /// </summary>
        public static string CardBusy {
            get {
                return ResourceManager.GetString("CardBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card exchange successful. We have sent your card information to your inbox.
        /// </summary>
        public static string CardCashoutSuccess {
            get {
                return ResourceManager.GetString("CardCashoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add money to user.
        /// </summary>
        public static string CardChargingNotAddAmount {
            get {
                return ResourceManager.GetString("CardChargingNotAddAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have recorded the card. Please wait.
        /// </summary>
        public static string CardChargingSuccess {
            get {
                return ResourceManager.GetString("CardChargingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card exchange system is busy.
        /// </summary>
        public static string CardCharingException {
            get {
                return ResourceManager.GetString("CardCharingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card face value.
        /// </summary>
        public static string CardCodeInValid {
            get {
                return ResourceManager.GetString("CardCodeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected the card value.
        /// </summary>
        public static string CardCodeRequired {
            get {
                return ResourceManager.GetString("CardCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact customer service for handling.
        /// </summary>
        public static string CardErrorContactCSKH {
            get {
                return ResourceManager.GetString("CardErrorContactCSKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card invalid.
        /// </summary>
        public static string CardInvalid {
            get {
                return ResourceManager.GetString("CardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card is updated status.
        /// </summary>
        public static string CardIsUpdateStatus {
            get {
                return ResourceManager.GetString("CardIsUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card fund is lacking.
        /// </summary>
        public static string CardLack {
            get {
                return ResourceManager.GetString("CardLack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has temporarily stopped accepting this card.
        /// </summary>
        public static string CardLock {
            get {
                return ResourceManager.GetString("CardLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has registered. Please wait for card approval.
        /// </summary>
        public static string CardNeedApproved {
            get {
                return ResourceManager.GetString("CardNeedApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Update Money.
        /// </summary>
        public static string CardNotUpdateMoney {
            get {
                return ResourceManager.GetString("CardNotUpdateMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card code contains only numeric characters.
        /// </summary>
        public static string CardNumberContainNumber {
            get {
                return ResourceManager.GetString("CardNumberContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card code contains only lowercase characters and numbers.
        /// </summary>
        public static string CardnumberInValid {
            get {
                return ResourceManager.GetString("CardnumberInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag code length is not suitable.
        /// </summary>
        public static string CardNumberLenghInValid {
            get {
                return ResourceManager.GetString("CardNumberLenghInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag code must not contain spaces.
        /// </summary>
        public static string CardNumberNotContainSpace {
            get {
                return ResourceManager.GetString("CardNumberNotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered the card code.
        /// </summary>
        public static string CardNumberRequired {
            get {
                return ResourceManager.GetString("CardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card is entered into the system more than the allowed number of times.
        /// </summary>
        public static string CardOverThree {
            get {
                return ResourceManager.GetString("CardOverThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeleteRateInvalid.
        /// </summary>
        public static string CardRateInValidate {
            get {
                return ResourceManager.GetString("CardRateInValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card serial length does not match.
        /// </summary>
        public static string CardSerialLenghInValid {
            get {
                return ResourceManager.GetString("CardSerialLenghInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card get status not success.
        /// </summary>
        public static string CardStatusNotSuccess {
            get {
                return ResourceManager.GetString("CardStatusNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card recharge successfully.
        /// </summary>
        public static string CardSuccessOnCharging {
            get {
                return ResourceManager.GetString("CardSuccessOnCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation and change of card successfully.
        /// </summary>
        public static string CardSwapCancelSuccess {
            get {
                return ResourceManager.GetString("CardSwapCancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redemption card not found.
        /// </summary>
        public static string CardSwapNotFound {
            get {
                return ResourceManager.GetString("CardSwapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid redemption card status.
        /// </summary>
        public static string CardSwapStatusInValid {
            get {
                return ResourceManager.GetString("CardSwapStatusInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System pauses card change {0}.
        /// </summary>
        public static string CardTelecomInActive {
            get {
                return ResourceManager.GetString("CardTelecomInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardTeleInValid.
        /// </summary>
        public static string CardTeleIDInValid {
            get {
                return ResourceManager.GetString("CardTeleIDInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a card type.
        /// </summary>
        public static string CardTypeRequired {
            get {
                return ResourceManager.GetString("CardTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not update.
        /// </summary>
        public static string CardUpdateError {
            get {
                return ResourceManager.GetString("CardUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CardUpdateOK {
            get {
                return ResourceManager.GetString("CardUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateStatus_2.
        /// </summary>
        public static string CardUpdateStatus_2 {
            get {
                return ResourceManager.GetString("CardUpdateStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update scratch card status -3.
        /// </summary>
        public static string CardUpdateStatus_Negative3 {
            get {
                return ResourceManager.GetString("CardUpdateStatus_Negative3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card update status 4 (refunded to customers).
        /// </summary>
        public static string CardUpdateStatus4 {
            get {
                return ResourceManager.GetString("CardUpdateStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status 3.
        /// </summary>
        public static string CardUpdateStatusOK_3 {
            get {
                return ResourceManager.GetString("CardUpdateStatusOK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card update status -1 ok.
        /// </summary>
        public static string CardUpdateStatusOKMinus_1 {
            get {
                return ResourceManager.GetString("CardUpdateStatusOKMinus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is syntactically incorrect. Thank you for using the service.
        /// </summary>
        public static string CommandNotRegister {
            get {
                return ResourceManager.GetString("CommandNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating too many accounts from one app.
        /// </summary>
        public static string CreateAccountManyTime {
            get {
                return ResourceManager.GetString("CreateAccountManyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create error log error.
        /// </summary>
        public static string CreateErrorLogError {
            get {
                return ResourceManager.GetString("CreateErrorLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP code is incorrect.
        /// </summary>
        public static string DeviceEmpty {
            get {
                return ResourceManager.GetString("DeviceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot contain spaces.
        /// </summary>
        public static string DisplayNameContainSpace {
            get {
                return ResourceManager.GetString("DisplayNameContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name contains only lowercase characters and numbers.
        /// </summary>
        public static string DisplayNameIncorrect {
            get {
                return ResourceManager.GetString("DisplayNameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display name should only contain between 6 and 16 characters.
        /// </summary>
        public static string DisplayNameLength {
            get {
                return ResourceManager.GetString("DisplayNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use.
        /// </summary>
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalidate.
        /// </summary>
        public static string EmailInValid {
            get {
                return ResourceManager.GetString("EmailInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You only have 1 time to enter the wrong giftcode before being locked out.
        /// </summary>
        public static string ERR_EXEED_WRONG_GIFTCODE_QUOTA {
            get {
                return ResourceManager.GetString("ERR_EXEED_WRONG_GIFTCODE_QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the wrong number of times allowed, you will be locked.
        /// </summary>
        public static string ERR_LOCK_EXEED_WRONG_GIFTCODE_QUOTA {
            get {
                return ResourceManager.GetString("ERR_LOCK_EXEED_WRONG_GIFTCODE_QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem/transfer after 24 hours since phone number registration. Or you need to reach 10vp to be redeemed immediately..
        /// </summary>
        public static string ERR_UPDATE_PHONE_LESS_24 {
            get {
                return ResourceManager.GetString("ERR_UPDATE_PHONE_LESS_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered wrong giftcode 10 times.
        /// </summary>
        public static string ERR_WRONG_GIFTCODE_10 {
            get {
                return ResourceManager.GetString("ERR_WRONG_GIFTCODE_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook information retrieval failed.
        /// </summary>
        public static string FacebookGetFail {
            get {
                return ResourceManager.GetString("FacebookGetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string FacebookIncorrect {
            get {
                return ResourceManager.GetString("FacebookIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered facebook account.
        /// </summary>
        public static string FBRegister {
            get {
                return ResourceManager.GetString("FBRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has not configured transaction fees.
        /// </summary>
        public static string FeeNotConfig {
            get {
                return ResourceManager.GetString("FeeNotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string FirstnameRequired {
            get {
                return ResourceManager.GetString("FirstnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function will open in a few days.
        /// </summary>
        public static string FunctionLock {
            get {
                return ResourceManager.GetString("FunctionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Account Incorrec.
        /// </summary>
        public static string GameAccountIncorrect {
            get {
                return ResourceManager.GetString("GameAccountIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gender.
        /// </summary>
        public static string GenderIncorrect {
            get {
                return ResourceManager.GetString("GenderIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information failed.
        /// </summary>
        public static string GetFail {
            get {
                return ResourceManager.GetString("GetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the gift code to the account with the error.
        /// </summary>
        public static string GiftCodeAmountValid {
            get {
                return ResourceManager.GetString("GiftCodeAmountValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gift code has expired.
        /// </summary>
        public static string GiftCodeExpired {
            get {
                return ResourceManager.GetString("GiftCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift code is incorrect.
        /// </summary>
        public static string GiftCodeInCorrect {
            get {
                return ResourceManager.GetString("GiftCodeInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gift code has been used.
        /// </summary>
        public static string GiftCodeInUse {
            get {
                return ResourceManager.GetString("GiftCodeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift code required to enter.
        /// </summary>
        public static string GiftCodeRequired {
            get {
                return ResourceManager.GetString("GiftCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the gift code successfully.
        /// </summary>
        public static string GiftCodeSuccess {
            get {
                return ResourceManager.GetString("GiftCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this campaign, each user can only use the gift code once.
        /// </summary>
        public static string GiftCodeUseOnlyOne {
            get {
                return ResourceManager.GetString("GiftCodeUseOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our system is busy, please try again later.
        /// </summary>
        public static string InProccessException {
            get {
                return ResourceManager.GetString("InProccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code.
        /// </summary>
        public static string InValidCaptCha {
            get {
                return ResourceManager.GetString("InValidCaptCha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transfer content.
        /// </summary>
        public static string InvalidNote {
            get {
                return ResourceManager.GetString("InvalidNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They can&apos;t be empty.
        /// </summary>
        public static string LastnameRequired {
            get {
                return ResourceManager.GetString("LastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed message.
        /// </summary>
        public static string MessageClearFail {
            get {
                return ResourceManager.GetString("MessageClearFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete message successfully.
        /// </summary>
        public static string MessageClearSuccess {
            get {
                return ResourceManager.GetString("MessageClearSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum amount should be {0}.
        /// </summary>
        public static string MinAmountTranfer {
            get {
                return ResourceManager.GetString("MinAmountTranfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone scratch card code contains only 12 characters.
        /// </summary>
        public static string MobilePhoneCardNumberLength {
            get {
                return ResourceManager.GetString("MobilePhoneCardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone series contains only 15 characters.
        /// </summary>
        public static string MobilePhoneSeriNumberLength {
            get {
                return ResourceManager.GetString("MobilePhoneSeriNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momo system is busy. Please come back later.
        /// </summary>
        public static string MOMOLOCK {
            get {
                return ResourceManager.GetString("MOMOLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System sending confirmation code is busy.
        /// </summary>
        public static string MSNErr {
            get {
                return ResourceManager.GetString("MSNErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name already used.
        /// </summary>
        public static string NameInUse {
            get {
                return ResourceManager.GetString("NameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country update successful.
        /// </summary>
        public static string NationChangeSuccess {
            get {
                return ResourceManager.GetString("NationChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country cannot be empty.
        /// </summary>
        public static string NationIsEmpty {
            get {
                return ResourceManager.GetString("NationIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password only needs to contain lowercase letters and numbers.
        /// </summary>
        public static string NewPasswordFormat {
            get {
                return ResourceManager.GetString("NewPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password from 6 to 16 characters.
        /// </summary>
        public static string NewPasswordLength {
            get {
                return ResourceManager.GetString("NewPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name containing keyword disallowed.
        /// </summary>
        public static string NickNameContainNotAlowString {
            get {
                return ResourceManager.GetString("NickNameContainNotAlowString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot contain username.
        /// </summary>
        public static string NickNameContainUsername {
            get {
                return ResourceManager.GetString("NickNameContainUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name cannot be empty.
        /// </summary>
        public static string NickNameEmpty {
            get {
                return ResourceManager.GetString("NickNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has updated its display name.
        /// </summary>
        public static string NickNameExist {
            get {
                return ResourceManager.GetString("NickNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name already used.
        /// </summary>
        public static string NickNameInUse {
            get {
                return ResourceManager.GetString("NickNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name length from 6 to 16 characters.
        /// </summary>
        public static string NickNameLength {
            get {
                return ResourceManager.GetString("NickNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name does not contain spaces.
        /// </summary>
        public static string NickNameNotContainSpace {
            get {
                return ResourceManager.GetString("NickNameNotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 50 characters.
        /// </summary>
        public static string NoteLengthOverMax {
            get {
                return ResourceManager.GetString("NoteLengthOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist in the system.
        /// </summary>
        public static string NOTINSERVICE {
            get {
                return ResourceManager.GetString("NOTINSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card loading port {0} is under maintenance.
        /// </summary>
        public static string NPPNotAcitve {
            get {
                return ResourceManager.GetString("NPPNotAcitve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is the same as the old password.
        /// </summary>
        public static string OldPasswordEqualNewPassword {
            get {
                return ResourceManager.GetString("OldPasswordEqualNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password from 6 to 16 characters.
        /// </summary>
        public static string OldPasswordLength {
            get {
                return ResourceManager.GetString("OldPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect.
        /// </summary>
        public static string OldPassWorldNotCorrect {
            get {
                return ResourceManager.GetString("OldPassWorldNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account does not have enough money to get the Otp code.
        /// </summary>
        public static string OTPBitNotEngough {
            get {
                return ResourceManager.GetString("OTPBitNotEngough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The otp sending system is busy.
        /// </summary>
        public static string OtpBusy {
            get {
                return ResourceManager.GetString("OtpBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered the otp code.
        /// </summary>
        public static string OtpEmpty {
            get {
                return ResourceManager.GetString("OtpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect otp code.
        /// </summary>
        public static string OtpIncorrect {
            get {
                return ResourceManager.GetString("OtpIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The otp character only accepts 6 for otp app, 7 for sms and 8 for AppSafe.
        /// </summary>
        public static string OtpLengthInValid {
            get {
                return ResourceManager.GetString("OtpLengthInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSafe has been linked to another account.
        /// </summary>
        public static string OtpSafeUsed {
            get {
                return ResourceManager.GetString("OtpSafeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        public static string ParamaterInvalid {
            get {
                return ResourceManager.GetString("ParamaterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and password repeat do not match!.
        /// </summary>
        public static string PassAndConfirmPassNotEqual {
            get {
                return ResourceManager.GetString("PassAndConfirmPassNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain spaces.
        /// </summary>
        public static string PasswordContainSpace {
            get {
                return ResourceManager.GetString("PasswordContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered your password.
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password contains only lowercase characters and numbers.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length from 6 to 16 characters.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a phone number.
        /// </summary>
        public static string PhoneEmpty {
            get {
                return ResourceManager.GetString("PhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is not in the correct format.
        /// </summary>
        public static string PhoneFormat {
            get {
                return ResourceManager.GetString("PhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string PhoneIncorrect {
            get {
                return ResourceManager.GetString("PhoneIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number already in use.
        /// </summary>
        public static string PhoneInUse {
            get {
                return ResourceManager.GetString("PhoneInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered phone number.
        /// </summary>
        public static string PhoneNotRegister {
            get {
                return ResourceManager.GetString("PhoneNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp code is incorrect.
        /// </summary>
        public static string PhoneNotRegisterToUseAppOtp {
            get {
                return ResourceManager.GetString("PhoneNotRegisterToUseAppOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused phone number.
        /// </summary>
        public static string PhoneNotUse {
            get {
                return ResourceManager.GetString("PhoneNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered phone number.
        /// </summary>
        public static string PhoneRegister {
            get {
                return ResourceManager.GetString("PhoneRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered phone number is different from the one entered.
        /// </summary>
        public static string PhoneRegisterDiffPhonePass {
            get {
                return ResourceManager.GetString("PhoneRegisterDiffPhonePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number does not exist in the AppSafe system.
        /// </summary>
        public static string PhoneSafeOtpEmty {
            get {
                return ResourceManager.GetString("PhoneSafeOtpEmty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number registered in AppSafe.
        /// </summary>
        public static string PhoneSafeOtpInUse {
            get {
                return ResourceManager.GetString("PhoneSafeOtpInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been updated with the phone number.
        /// </summary>
        public static string PhoneUpdateNeedEmpty {
            get {
                return ResourceManager.GetString("PhoneUpdateNeedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid phone number.
        /// </summary>
        public static string PhoneValid {
            get {
                return ResourceManager.GetString("PhoneValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system does not support this type of mobile number.
        /// </summary>
        public static string PhoneVietnammobileNotSupport {
            get {
                return ResourceManager.GetString("PhoneVietnammobileNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused phone number in AppSafe system.
        /// </summary>
        public static string SafeIDNotCreate {
            get {
                return ResourceManager.GetString("SafeIDNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully linked AppSafe account.
        /// </summary>
        public static string SafeIDSuccess {
            get {
                return ResourceManager.GetString("SafeIDSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Otp code is {0} limited to use within 5 minutes.
        /// </summary>
        public static string SafeNotiyType10 {
            get {
                return ResourceManager.GetString("SafeNotiyType10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept only authentication codes sent to the AppSafe system.
        /// </summary>
        public static string SafeOtpOnlyAccept {
            get {
                return ResourceManager.GetString("SafeOtpOnlyAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving transaction history.
        /// </summary>
        public static string SaveLogError {
            get {
                return ResourceManager.GetString("SaveLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts need to secure their phone number to use this function.
        /// </summary>
        public static string SecurityInValid {
            get {
                return ResourceManager.GetString("SecurityInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial contains only lowercase characters and numbers.
        /// </summary>
        public static string SerialCardInvalid {
            get {
                return ResourceManager.GetString("SerialCardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial card invalid.
        /// </summary>
        public static string SerialInvalid {
            get {
                return ResourceManager.GetString("SerialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial contains only characters and numbers.
        /// </summary>
        public static string SerialNumberContainNumber {
            get {
                return ResourceManager.GetString("SerialNumberContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card serial cannot contain spaces.
        /// </summary>
        public static string SerialNumberNotContainSpace {
            get {
                return ResourceManager.GetString("SerialNumberNotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered the card serial number.
        /// </summary>
        public static string SerialNumberRequired {
            get {
                return ResourceManager.GetString("SerialNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature incorrect.
        /// </summary>
        public static string SignatureIncorrect {
            get {
                return ResourceManager.GetString("SignatureIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only accept otp codes sent from SMS.
        /// </summary>
        public static string SmsOtpOnlyAccept {
            get {
                return ResourceManager.GetString("SmsOtpOnlyAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause account registration..
        /// </summary>
        public static string STOPREGISTER {
            get {
                return ResourceManager.GetString("STOPREGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token cannot be empty.
        /// </summary>
        public static string TokenEmtpy {
            get {
                return ResourceManager.GetString("TokenEmtpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money transfer successful.
        /// </summary>
        public static string TranferBitSuccess {
            get {
                return ResourceManager.GetString("TranferBitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer money over limit within the day.
        /// </summary>
        public static string TranferOverMoney {
            get {
                return ResourceManager.GetString("TranferOverMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in yet.
        /// </summary>
        public static string UnAuthorized {
            get {
                return ResourceManager.GetString("UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmount successful.
        /// </summary>
        public static string UnSafeIDSuccess {
            get {
                return ResourceManager.GetString("UnSafeIDSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update card status 3 error.
        /// </summary>
        public static string UpdateCardStatus3Error {
            get {
                return ResourceManager.GetString("UpdateCardStatus3Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name updated successfully.
        /// </summary>
        public static string UpdateNickNameSuccess {
            get {
                return ResourceManager.GetString("UpdateNickNameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security update successful.
        /// </summary>
        public static string UpdateSecuritySucess {
            get {
                return ResourceManager.GetString("UpdateSecuritySucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status success error.
        /// </summary>
        public static string UpdateStatusSuccessError {
            get {
                return ResourceManager.GetString("UpdateStatusSuccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not found by request id.
        /// </summary>
        public static string UserCardNotFind {
            get {
                return ResourceManager.GetString("UserCardNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling card change failed.
        /// </summary>
        public static string UserCardSwapCancelFail {
            get {
                return ResourceManager.GetString("UserCardSwapCancelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has redeemed VP points.
        /// </summary>
        public static string UserChangeVP {
            get {
                return ResourceManager.GetString("UserChangeVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is Invalid.
        /// </summary>
        public static string UserInValid {
            get {
                return ResourceManager.GetString("UserInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string UserNameAndPasswordExist {
            get {
                return ResourceManager.GetString("UserNameAndPasswordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain display name.
        /// </summary>
        public static string UsernameContainDisplayname {
            get {
                return ResourceManager.GetString("UsernameContainDisplayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username contains keywords not allowed.
        /// </summary>
        public static string UserNameContainsNotAllowString {
            get {
                return ResourceManager.GetString("UserNameContainsNotAllowString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain spaces.
        /// </summary>
        public static string UserNameContainSpace {
            get {
                return ResourceManager.GetString("UserNameContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank.
        /// </summary>
        public static string UsernameEmpty {
            get {
                return ResourceManager.GetString("UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character name is the same as the login name.
        /// </summary>
        public static string UserNameEqualNickName {
            get {
                return ResourceManager.GetString("UserNameEqualNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username contains only alphanumeric characters.
        /// </summary>
        public static string UsernameIncorrect {
            get {
                return ResourceManager.GetString("UsernameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already used.
        /// </summary>
        public static string UserNameInUse {
            get {
                return ResourceManager.GetString("UserNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username length from 6 to 16 characters.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string UserNameOrPassInCorrect {
            get {
                return ResourceManager.GetString("UserNameOrPassInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receiving account cannot be empty.
        /// </summary>
        public static string UserNameTranferInvalid {
            get {
                return ResourceManager.GetString("UserNameTranferInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked.
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist in the system.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get user&apos;s rank.
        /// </summary>
        public static string UserNotGetRank {
            get {
                return ResourceManager.GetString("UserNotGetRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is not rated yet.
        /// </summary>
        public static string UserNotRanked {
            get {
                return ResourceManager.GetString("UserNotRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is Invalid.
        /// </summary>
        public static string UserNotValid {
            get {
                return ResourceManager.GetString("UserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not eligible to redeem VP points.
        /// </summary>
        public static string UserRankNotVerify {
            get {
                return ResourceManager.GetString("UserRankNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot transfer to yourself.
        /// </summary>
        public static string UserTranferEqualUser {
            get {
                return ResourceManager.GetString("UserTranferEqualUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmitter does not exist.
        /// </summary>
        public static string UserTranferNotExist {
            get {
                return ResourceManager.GetString("UserTranferNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scratch card code is only 13 or 15 characters.
        /// </summary>
        public static string ViettelCardNumberLength {
            get {
                return ResourceManager.GetString("ViettelCardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is busy. Please come back later.
        /// </summary>
        public static string VIETTELPAYLOCK {
            get {
                return ResourceManager.GetString("VIETTELPAYLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your series contains only 11 or 14 characters.
        /// </summary>
        public static string ViettelSeriNumberLength {
            get {
                return ResourceManager.GetString("ViettelSeriNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scratch card code is only 12 or 14 characters.
        /// </summary>
        public static string VinaphoneCardNumberLength {
            get {
                return ResourceManager.GetString("VinaphoneCardNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The series is only 12 or 14 characters.
        /// </summary>
        public static string VinaphoneSeriNumberLength {
            get {
                return ResourceManager.GetString("VinaphoneSeriNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redemption system is busy. Please contact me again later.
        /// </summary>
        public static string VPFail {
            get {
                return ResourceManager.GetString("VPFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current number of points is not enough to redeem.
        /// </summary>
        public static string VPNotEnough {
            get {
                return ResourceManager.GetString("VPNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully received rewards.
        /// </summary>
        public static string VPSuccess {
            get {
                return ResourceManager.GetString("VPSuccess", resourceCulture);
            }
        }
    }
}
