//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsTraditionGame.Utilities.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsTraditionGame.Utilities.Messages.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại.
        /// </summary>
        public static string AccountExist {
            get {
                return ResourceManager.GetString("AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa.
        /// </summary>
        public static string AccountLock {
            get {
                return ResourceManager.GetString("AccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nhận Q không tồn tại.
        /// </summary>
        public static string AccountReceiveNotExist {
            get {
                return ResourceManager.GetString("AccountReceiveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không cấu hình gửi otp.
        /// </summary>
        public static string AcountNotConfigOtp {
            get {
                return ResourceManager.GetString("AcountNotConfigOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi quà không thành công.
        /// </summary>
        public static string AdBoxFail {
            get {
                return ResourceManager.GetString("AdBoxFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại quà đổi không hợp lệ.
        /// </summary>
        public static string AdBoxGiftCodeInValid {
            get {
                return ResourceManager.GetString("AdBoxGiftCodeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi quà thành công.
        /// </summary>
        public static string AdBoxSuccess {
            get {
                return ResourceManager.GetString("AdBoxSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đại lý đã được sử dụng.
        /// </summary>
        public static string AgencyCodeInUse {
            get {
                return ResourceManager.GetString("AgencyCodeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý đã bị khóa.
        /// </summary>
        public static string AgencyDisable {
            get {
                return ResourceManager.GetString("AgencyDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý đã tồn tại.
        /// </summary>
        public static string AgencyExist {
            get {
                return ResourceManager.GetString("AgencyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link facebook đã được sử dụng.
        /// </summary>
        public static string AgencyFBLinkInUse {
            get {
                return ResourceManager.GetString("AgencyFBLinkInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý đã bị khóa.
        /// </summary>
        public static string AgencyLock {
            get {
                return ResourceManager.GetString("AgencyLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý không tồn tại.
        /// </summary>
        public static string AgencyNotExist {
            get {
                return ResourceManager.GetString("AgencyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật đại lý đã được sử dụng.
        /// </summary>
        public static string AgencySecretInUse {
            get {
                return ResourceManager.GetString("AgencySecretInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Q yêu cầu nhập.
        /// </summary>
        public static string AmountInValid {
            get {
                return ResourceManager.GetString("AmountInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ Q để đổi thẻ.
        /// </summary>
        public static string AmountNotEnoghToCardExchange {
            get {
                return ResourceManager.GetString("AmountNotEnoghToCardExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Két không đủ Q để  rút.
        /// </summary>
        public static string AmountNotEnoughToOpenSafe {
            get {
                return ResourceManager.GetString("AmountNotEnoughToOpenSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ Q để chuyển vào két.
        /// </summary>
        public static string AmountNotEnoughToSafe {
            get {
                return ResourceManager.GetString("AmountNotEnoughToSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Q không hợp lệ.
        /// </summary>
        public static string AmountNotValid {
            get {
                return ResourceManager.GetString("AmountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ Q để thực hiện giao dịch.
        /// </summary>
        public static string AmountNotValidToTranferBit {
            get {
                return ResourceManager.GetString("AmountNotValidToTranferBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay bạn đã test đủ rồi. Vui lòng quay lại vào ngày mai. Cám ơn bạn đã ủng hộ.
        /// </summary>
        public static string AnphaMsg {
            get {
                return ResourceManager.GetString("AnphaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh đại diện không hợp lệ.
        /// </summary>
        public static string AvatarIncorrect {
            get {
                return ResourceManager.GetString("AvatarIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ Q để thực hiện giao dịch.
        /// </summary>
        public static string BalanceNotEnough {
            get {
                return ResourceManager.GetString("BalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không hợp lệ .
        /// </summary>
        public static string BirthdayIncorrect {
            get {
                return ResourceManager.GetString("BirthdayIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận thưởng mốc thành công.
        /// </summary>
        public static string Bom1AddSuccess {
            get {
                return ResourceManager.GetString("Bom1AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận thưởng mốc thất bại.
        /// </summary>
        public static string Bom1AdFail {
            get {
                return ResourceManager.GetString("Bom1AdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức nhận thưởng mốc đã hết.
        /// </summary>
        public static string Bom1OverQuata {
            get {
                return ResourceManager.GetString("Bom1OverQuata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã nhận thưởng mốc.
        /// </summary>
        public static string Bom1UserReceived {
            get {
                return ResourceManager.GetString("Bom1UserReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến dịch gift code không tồn tại.
        /// </summary>
        public static string CampaignNotExist {
            get {
                return ResourceManager.GetString("CampaignNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quỹ chiến dịch đã hết.
        /// </summary>
        public static string CampaignOutMoney {
            get {
                return ResourceManager.GetString("CampaignOutMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực không thể để trống.
        /// </summary>
        public static string CapchaRequired {
            get {
                return ResourceManager.GetString("CapchaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống bận.
        /// </summary>
        public static string CardBusy {
            get {
                return ResourceManager.GetString("CardBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi thẻ thành công.Chúng tôi đã gửi thông tin thẻ vào hòm thư của bạn.
        /// </summary>
        public static string CardCashoutSuccess {
            get {
                return ResourceManager.GetString("CardCashoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cộng tiền cho user.
        /// </summary>
        public static string CardChargingNotAddAmount {
            get {
                return ResourceManager.GetString("CardChargingNotAddAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đã ghi nhận thẻ .Bạn vui lòng đợi.
        /// </summary>
        public static string CardChargingSuccess {
            get {
                return ResourceManager.GetString("CardChargingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đổi thẻ đang bận.
        /// </summary>
        public static string CardCharingException {
            get {
                return ResourceManager.GetString("CardCharingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá thẻ không hợp lệ.
        /// </summary>
        public static string CardCodeInValid {
            get {
                return ResourceManager.GetString("CardCodeInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn mệnh giá thẻ.
        /// </summary>
        public static string CardCodeRequired {
            get {
                return ResourceManager.GetString("CardCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ chăm sóc khách hàng để xử lý.
        /// </summary>
        public static string CardErrorContactCSKH {
            get {
                return ResourceManager.GetString("CardErrorContactCSKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card invalid.
        /// </summary>
        public static string CardInvalid {
            get {
                return ResourceManager.GetString("CardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card is updated status.
        /// </summary>
        public static string CardIsUpdateStatus {
            get {
                return ResourceManager.GetString("CardIsUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quỹ thẻ thiếu.
        /// </summary>
        public static string CardLack {
            get {
                return ResourceManager.GetString("CardLack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống tạm dừng ghi nhận thẻ này.
        /// </summary>
        public static string CardLock {
            get {
                return ResourceManager.GetString("CardLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đã ghi nhận .Xin chờ duyệt thẻ.
        /// </summary>
        public static string CardNeedApproved {
            get {
                return ResourceManager.GetString("CardNeedApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Update Money.
        /// </summary>
        public static string CardNotUpdateMoney {
            get {
                return ResourceManager.GetString("CardNotUpdateMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ chỉ chứa kí tự số.
        /// </summary>
        public static string CardNumberContainNumber {
            get {
                return ResourceManager.GetString("CardNumberContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mã thẻ không phù hợp.
        /// </summary>
        public static string CardNumberLenghInValid {
            get {
                return ResourceManager.GetString("CardNumberLenghInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ không được chứa khoảng trắng.
        /// </summary>
        public static string CardNumberNotContainSpace {
            get {
                return ResourceManager.GetString("CardNumberNotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mã thẻ.
        /// </summary>
        public static string CardNumberRequired {
            get {
                return ResourceManager.GetString("CardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ được nhập vào hệ thống quá số lần cho phép.
        /// </summary>
        public static string CardOverThree {
            get {
                return ResourceManager.GetString("CardOverThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài serial thẻ không phù hợp.
        /// </summary>
        public static string CardSerialLenghInValid {
            get {
                return ResourceManager.GetString("CardSerialLenghInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card get status not success.
        /// </summary>
        public static string CardStatusNotSuccess {
            get {
                return ResourceManager.GetString("CardStatusNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp thẻ thành công.
        /// </summary>
        public static string CardSuccessOnCharging {
            get {
                return ResourceManager.GetString("CardSuccessOnCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đổi thẻ thành công.
        /// </summary>
        public static string CardSwapCancelSuccess {
            get {
                return ResourceManager.GetString("CardSwapCancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ đổi thưởng không tìm thấy.
        /// </summary>
        public static string CardSwapNotFound {
            get {
                return ResourceManager.GetString("CardSwapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái thẻ đổi không hợp lệ.
        /// </summary>
        public static string CardSwapStatusInValid {
            get {
                return ResourceManager.GetString("CardSwapStatusInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống tạm dừng đổi thẻ {0}.
        /// </summary>
        public static string CardTelecomInActive {
            get {
                return ResourceManager.GetString("CardTelecomInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardTeleInValid.
        /// </summary>
        public static string CardTeleIDInValid {
            get {
                return ResourceManager.GetString("CardTeleIDInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn loại thẻ.
        /// </summary>
        public static string CardTypeRequired {
            get {
                return ResourceManager.GetString("CardTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not update.
        /// </summary>
        public static string CardUpdateError {
            get {
                return ResourceManager.GetString("CardUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CardUpdateOK {
            get {
                return ResourceManager.GetString("CardUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateStatus_2.
        /// </summary>
        public static string CardUpdateStatus_2 {
            get {
                return ResourceManager.GetString("CardUpdateStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status 3.
        /// </summary>
        public static string CardUpdateStatusOK_3 {
            get {
                return ResourceManager.GetString("CardUpdateStatusOK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card update status -1 ok.
        /// </summary>
        public static string CardUpdateStatusOKMinus_1 {
            get {
                return ResourceManager.GetString("CardUpdateStatusOKMinus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo quá nhiều tài khoả từ một ứng dụng.
        /// </summary>
        public static string CreateAccountManyTime {
            get {
                return ResourceManager.GetString("CreateAccountManyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create error log error.
        /// </summary>
        public static string CreateErrorLogError {
            get {
                return ResourceManager.GetString("CreateErrorLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị không thể chứa khoảng trắng.
        /// </summary>
        public static string DisplayNameContainSpace {
            get {
                return ResourceManager.GetString("DisplayNameContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị chỉ chứa kí tự thường và số.
        /// </summary>
        public static string DisplayNameIncorrect {
            get {
                return ResourceManager.GetString("DisplayNameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị chỉ chứa từ khoảng  6 tới 16 kí tự.
        /// </summary>
        public static string DisplayNameLength {
            get {
                return ResourceManager.GetString("DisplayNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  không thể trống.
        /// </summary>
        public static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng.
        /// </summary>
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string EmailInValid {
            get {
                return ResourceManager.GetString("EmailInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thông tin facebook không thành công.
        /// </summary>
        public static string FacebookGetFail {
            get {
                return ResourceManager.GetString("FacebookGetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string FacebookIncorrect {
            get {
                return ResourceManager.GetString("FacebookIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản facebook đã đăng ký.
        /// </summary>
        public static string FBRegister {
            get {
                return ResourceManager.GetString("FBRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống chưa cấu hình phí giao dịch.
        /// </summary>
        public static string FeeNotConfig {
            get {
                return ResourceManager.GetString("FeeNotConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng sẽ mở sau 1 vài ngày.
        /// </summary>
        public static string FunctionLock {
            get {
                return ResourceManager.GetString("FunctionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Account Incorrec.
        /// </summary>
        public static string GameAccountIncorrect {
            get {
                return ResourceManager.GetString("GameAccountIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính không hợp lệ .
        /// </summary>
        public static string GenderIncorrect {
            get {
                return ResourceManager.GetString("GenderIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thông tin không thành công.
        /// </summary>
        public static string GetFail {
            get {
                return ResourceManager.GetString("GetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng tiền gift code vào tài khoản xảy ra lỗi.
        /// </summary>
        public static string GiftCodeAmountValid {
            get {
                return ResourceManager.GetString("GiftCodeAmountValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã gift code đã hết hạn sử dụng.
        /// </summary>
        public static string GiftCodeExpired {
            get {
                return ResourceManager.GetString("GiftCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã gift code không chính xác.
        /// </summary>
        public static string GiftCodeInCorrect {
            get {
                return ResourceManager.GetString("GiftCodeInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã gift code đã được sử dụng.
        /// </summary>
        public static string GiftCodeInUse {
            get {
                return ResourceManager.GetString("GiftCodeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã gift code yêu cầu nhập.
        /// </summary>
        public static string GiftCodeRequired {
            get {
                return ResourceManager.GetString("GiftCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã gift code thành công.
        /// </summary>
        public static string GiftCodeSuccess {
            get {
                return ResourceManager.GetString("GiftCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong chiến dịch này mỗi người dùng chỉ được sử dụng một lần gift code.
        /// </summary>
        public static string GiftCodeUseOnlyOne {
            get {
                return ResourceManager.GetString("GiftCodeUseOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống của chúng tôi đang bận, xin bạn vui lòng thử lại sau.
        /// </summary>
        public static string InProccessException {
            get {
                return ResourceManager.GetString("InProccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận không đúng.
        /// </summary>
        public static string InValidCaptCha {
            get {
                return ResourceManager.GetString("InValidCaptCha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Q tối thiểu phải là {0} .
        /// </summary>
        public static string MinAmountTranfer {
            get {
                return ResourceManager.GetString("MinAmountTranfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị đã có người sử dụng.
        /// </summary>
        public static string NameInUse {
            get {
                return ResourceManager.GetString("NameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu  mới chỉ cần chứa kí tự thường và số .
        /// </summary>
        public static string NewPasswordFormat {
            get {
                return ResourceManager.GetString("NewPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới từ 6 tới 16 ký tự.
        /// </summary>
        public static string NewPasswordLength {
            get {
                return ResourceManager.GetString("NewPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị chứa từ khóa không cho phép.
        /// </summary>
        public static string NickNameContainNotAlowString {
            get {
                return ResourceManager.GetString("NickNameContainNotAlowString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị không thể chứa tên đăng nhập.
        /// </summary>
        public static string NickNameContainUsername {
            get {
                return ResourceManager.GetString("NickNameContainUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị không được để trống.
        /// </summary>
        public static string NickNameEmpty {
            get {
                return ResourceManager.GetString("NickNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã cập nhật tên hiển thị.
        /// </summary>
        public static string NickNameExist {
            get {
                return ResourceManager.GetString("NickNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân vật đã được sử dụng.
        /// </summary>
        public static string NickNameInUse {
            get {
                return ResourceManager.GetString("NickNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tên hiển thị từ 6 tới 16 ký tự.
        /// </summary>
        public static string NickNameLength {
            get {
                return ResourceManager.GetString("NickNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị không chứa khoảng trắng.
        /// </summary>
        public static string NickNameNotContainSpace {
            get {
                return ResourceManager.GetString("NickNameNotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả không thể vượt quá 50 kí tự.
        /// </summary>
        public static string NoteLengthOverMax {
            get {
                return ResourceManager.GetString("NoteLengthOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng nạp thẻ {0} đang bảo trì.
        /// </summary>
        public static string NPPNotAcitve {
            get {
                return ResourceManager.GetString("NPPNotAcitve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới trùng với mật khẩu cũ.
        /// </summary>
        public static string OldPasswordEqualNewPassword {
            get {
                return ResourceManager.GetString("OldPasswordEqualNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ từ 6 tới 16 ký tự.
        /// </summary>
        public static string OldPasswordLength {
            get {
                return ResourceManager.GetString("OldPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không chính xác .
        /// </summary>
        public static string OldPassWorldNotCorrect {
            get {
                return ResourceManager.GetString("OldPassWorldNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ Q lấy mã Otp.
        /// </summary>
        public static string OTPBitNotEngough {
            get {
                return ResourceManager.GetString("OTPBitNotEngough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống gửi otp đang bận.
        /// </summary>
        public static string OtpBusy {
            get {
                return ResourceManager.GetString("OtpBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mã otp.
        /// </summary>
        public static string OtpEmpty {
            get {
                return ResourceManager.GetString("OtpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã otp không chính xác.
        /// </summary>
        public static string OtpIncorrect {
            get {
                return ResourceManager.GetString("OtpIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số không hợp lệ.
        /// </summary>
        public static string ParamaterInvalid {
            get {
                return ResourceManager.GetString("ParamaterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không thể chứa khoảng trắng.
        /// </summary>
        public static string PasswordContainSpace {
            get {
                return ResourceManager.GetString("PasswordContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mật khẩu .
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu chỉ chứ kí tự thường và số.
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mật khẩu từ 6 tới 16 ký tự.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập số điện thoại.
        /// </summary>
        public static string PhoneEmpty {
            get {
                return ResourceManager.GetString("PhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng định dạng.
        /// </summary>
        public static string PhoneFormat {
            get {
                return ResourceManager.GetString("PhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        public static string PhoneIncorrect {
            get {
                return ResourceManager.GetString("PhoneIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại có người sử dụng.
        /// </summary>
        public static string PhoneInUse {
            get {
                return ResourceManager.GetString("PhoneInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại chưa được đăng ký.
        /// </summary>
        public static string PhoneNotRegister {
            get {
                return ResourceManager.GetString("PhoneNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại chưa được sử dụng.
        /// </summary>
        public static string PhoneNotUse {
            get {
                return ResourceManager.GetString("PhoneNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được đăng ký.
        /// </summary>
        public static string PhoneRegister {
            get {
                return ResourceManager.GetString("PhoneRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đăng ký khác số điện đã nhập.
        /// </summary>
        public static string PhoneRegisterDiffPhonePass {
            get {
                return ResourceManager.GetString("PhoneRegisterDiffPhonePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được cập nhật số điện thoại.
        /// </summary>
        public static string PhoneUpdateNeedEmpty {
            get {
                return ResourceManager.GetString("PhoneUpdateNeedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi lưu lịch sử giao dịch.
        /// </summary>
        public static string SaveLogError {
            get {
                return ResourceManager.GetString("SaveLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial card invalid.
        /// </summary>
        public static string SerialInvalid {
            get {
                return ResourceManager.GetString("SerialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial chỉ chứ kí tự là số.
        /// </summary>
        public static string SerialNumberContainNumber {
            get {
                return ResourceManager.GetString("SerialNumberContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial thẻ không được chứa khoảng trắng.
        /// </summary>
        public static string SerialNumberNotContainSpace {
            get {
                return ResourceManager.GetString("SerialNumberNotContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập số serial thẻ.
        /// </summary>
        public static string SerialNumberRequired {
            get {
                return ResourceManager.GetString("SerialNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signature incorrect.
        /// </summary>
        public static string SignatureIncorrect {
            get {
                return ResourceManager.GetString("SignatureIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Q thành công.
        /// </summary>
        public static string TranferBitSuccess {
            get {
                return ResourceManager.GetString("TranferBitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Q vượt hạng mức trong ngày.
        /// </summary>
        public static string TranferOverMoney {
            get {
                return ResourceManager.GetString("TranferOverMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng nhập.
        /// </summary>
        public static string UnAuthorized {
            get {
                return ResourceManager.GetString("UnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update card status 3 error.
        /// </summary>
        public static string UpdateCardStatus3Error {
            get {
                return ResourceManager.GetString("UpdateCardStatus3Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị cập nhật thành công.
        /// </summary>
        public static string UpdateNickNameSuccess {
            get {
                return ResourceManager.GetString("UpdateNickNameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bảo mật thành công.
        /// </summary>
        public static string UpdateSecuritySucess {
            get {
                return ResourceManager.GetString("UpdateSecuritySucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status success error.
        /// </summary>
        public static string UpdateStatusSuccessError {
            get {
                return ResourceManager.GetString("UpdateStatusSuccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không tìm thấy thẻ theo request id.
        /// </summary>
        public static string UserCardNotFind {
            get {
                return ResourceManager.GetString("UserCardNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đổi thẻ thất bại.
        /// </summary>
        public static string UserCardSwapCancelFail {
            get {
                return ResourceManager.GetString("UserCardSwapCancelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã đổi điểm VP.
        /// </summary>
        public static string UserChangeVP {
            get {
                return ResourceManager.GetString("UserChangeVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ.
        /// </summary>
        public static string UserInValid {
            get {
                return ResourceManager.GetString("UserInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập chứa từ khóa không cho phép.
        /// </summary>
        public static string UserNameContainsNotAllowString {
            get {
                return ResourceManager.GetString("UserNameContainsNotAllowString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không thể chứa khoảng trắng.
        /// </summary>
        public static string UserNameContainSpace {
            get {
                return ResourceManager.GetString("UserNameContainSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không để trống.
        /// </summary>
        public static string UsernameEmpty {
            get {
                return ResourceManager.GetString("UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân vật trùng với tên đăng nhập.
        /// </summary>
        public static string UserNameEqualNickName {
            get {
                return ResourceManager.GetString("UserNameEqualNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập chỉ chứa kí tự số và chữ.
        /// </summary>
        public static string UsernameIncorrect {
            get {
                return ResourceManager.GetString("UsernameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng  nhập đã có người sử dụng.
        /// </summary>
        public static string UserNameInUse {
            get {
                return ResourceManager.GetString("UserNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài tên đăng nhập từ 6 tới 16 ký tự.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string UserNameOrPassInCorrect {
            get {
                return ResourceManager.GetString("UserNameOrPassInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nhận Q không thể để trống.
        /// </summary>
        public static string UserNameTranferInvalid {
            get {
                return ResourceManager.GetString("UserNameTranferInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản  đã bị khóa.
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại trong hệ thống.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được xếp hạng.
        /// </summary>
        public static string UserNotRanked {
            get {
                return ResourceManager.GetString("UserNotRanked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ.
        /// </summary>
        public static string UserNotValid {
            get {
                return ResourceManager.GetString("UserNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn chưa đủ điều kiện để đổi điểm VP.
        /// </summary>
        public static string UserRankNotVerify {
            get {
                return ResourceManager.GetString("UserRankNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể chuyển cho chính bạn.
        /// </summary>
        public static string UserTranferEqualUser {
            get {
                return ResourceManager.GetString("UserTranferEqualUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người chuyển không tồn tại.
        /// </summary>
        public static string UserTranferNotExist {
            get {
                return ResourceManager.GetString("UserTranferNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đổi thưởng đang bận. Vui lòng liên hệ lại sau.
        /// </summary>
        public static string VPFail {
            get {
                return ResourceManager.GetString("VPFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điểm hiện tại không đủ để quy đổi.
        /// </summary>
        public static string VPNotEnough {
            get {
                return ResourceManager.GetString("VPNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận thưởng thành công.
        /// </summary>
        public static string VPSuccess {
            get {
                return ResourceManager.GetString("VPSuccess", resourceCulture);
            }
        }
    }
}
