//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsWebGame.CSKH.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsWebGame.CSKH.Utils.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đại lý yêu cầu nhập.
        /// </summary>
        internal static string AccountCodeRequired {
            get {
                return ResourceManager.GetString("AccountCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản đã tồn tại.
        /// </summary>
        internal static string AccountExist {
            get {
                return ResourceManager.GetString("AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không chính xác.
        /// </summary>
        internal static string AccountInvalid {
            get {
                return ResourceManager.GetString("AccountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản yêu cầu nhập.
        /// </summary>
        internal static string AccountRequired {
            get {
                return ResourceManager.GetString("AccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Bit muốn chuyển không nằm trong khoảng cấu hình.
        /// </summary>
        internal static string AdminAmountInvalid {
            get {
                return ResourceManager.GetString("AdminAmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ Bit để tạo gift code.
        /// </summary>
        internal static string AdminNotEnoughMoneyToCreateGiftCode {
            get {
                return ResourceManager.GetString("AdminNotEnoughMoneyToCreateGiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản admin không tồn tại.
        /// </summary>
        internal static string AdminNotExist {
            get {
                return ResourceManager.GetString("AdminNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý đã bị khóa.
        /// </summary>
        internal static string AgencyDisabled {
            get {
                return ResourceManager.GetString("AgencyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý đã tồn tại.
        /// </summary>
        internal static string AgencyExist {
            get {
                return ResourceManager.GetString("AgencyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý có giao dịch không thể xóa!.
        /// </summary>
        internal static string AgencyHasTransaction {
            get {
                return ResourceManager.GetString("AgencyHasTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp độ đại lý sai.
        /// </summary>
        internal static string AgencyLevelInvalid {
            get {
                return ResourceManager.GetString("AgencyLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý đã bị khóa.
        /// </summary>
        internal static string AgencyLock {
            get {
                return ResourceManager.GetString("AgencyLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý không tồn tại.
        /// </summary>
        internal static string AgencyNotExist {
            get {
                return ResourceManager.GetString("AgencyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn đại lý.
        /// </summary>
        internal static string AgencyParentRequired {
            get {
                return ResourceManager.GetString("AgencyParentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa lựa chọn đại lý.
        /// </summary>
        internal static string AgencyRequired {
            get {
                return ResourceManager.GetString("AgencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đại lý sai.
        /// </summary>
        internal static string AgencyStatusInvalid {
            get {
                return ResourceManager.GetString("AgencyStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền không đủ để thực hiện giao dịch.
        /// </summary>
        internal static string AmountInvalid {
            get {
                return ResourceManager.GetString("AmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Bit giao dịch yêu cầu nhập.
        /// </summary>
        internal static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực yêu cầu nhập.
        /// </summary>
        internal static string AreaRequired {
            get {
                return ResourceManager.GetString("AreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hiện vật yêu cầu nhập.
        /// </summary>
        internal static string ArtifactCodeRequired {
            get {
                return ResourceManager.GetString("ArtifactCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiện vật yêu cầu nhập.
        /// </summary>
        internal static string ArtifactNameRequired {
            get {
                return ResourceManager.GetString("ArtifactNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ thẻ ngân hàng yêu cầu nhập.
        /// </summary>
        internal static string BankAccountNameRequired {
            get {
                return ResourceManager.GetString("BankAccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngân hàng yêu cầu nhập.
        /// </summary>
        internal static string BankAccountNoRequired {
            get {
                return ResourceManager.GetString("BankAccountNoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh ngân hàng yêu cầu nhập.
        /// </summary>
        internal static string BankAddressRequired {
            get {
                return ResourceManager.GetString("BankAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản đã tồn tại.
        /// </summary>
        internal static string BankCodeExist {
            get {
                return ResourceManager.GetString("BankCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại ngân hàng yêu cầu nhập.
        /// </summary>
        internal static string BankRequired {
            get {
                return ResourceManager.GetString("BankRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chiến dịch yêu cầu nhập.
        /// </summary>
        internal static string CampaignCodeRequired {
            get {
                return ResourceManager.GetString("CampaignCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến dịch tạo gift code đã tồn tại.
        /// </summary>
        internal static string CampaignExist {
            get {
                return ResourceManager.GetString("CampaignExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến dịch  không hợp lệ.
        /// </summary>
        internal static string CampaignInvalid {
            get {
                return ResourceManager.GetString("CampaignInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chiến dịch yêu cầu nhập.
        /// </summary>
        internal static string CampaignNameRequired {
            get {
                return ResourceManager.GetString("CampaignNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến dịch tạo gift code yêu cầu nhập.
        /// </summary>
        internal static string CampaignRequired {
            get {
                return ResourceManager.GetString("CampaignRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ cào đã tồn tại.
        /// </summary>
        internal static string CardCodeExist {
            get {
                return ResourceManager.GetString("CardCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ cào yêu cầu nhập.
        /// </summary>
        internal static string CardCodeRequired {
            get {
                return ResourceManager.GetString("CardCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thẻ cào yêu cầu nhập.
        /// </summary>
        internal static string CardNameRequired {
            get {
                return ResourceManager.GetString("CardNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị thẻ nạp sai định dạng.
        /// </summary>
        internal static string CardValueInvalid {
            get {
                return ResourceManager.GetString("CardValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị thẻ cào yêu cầu nhập.
        /// </summary>
        internal static string CardValueRequired {
            get {
                return ResourceManager.GetString("CardValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung yêu cầu nhập.
        /// </summary>
        internal static string ContentRequired {
            get {
                return ResourceManager.GetString("ContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chăm sóc khách hàng đã tồn tại.
        /// </summary>
        internal static string CSKHExist {
            get {
                return ResourceManager.GetString("CSKHExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi thất bại.
        /// </summary>
        internal static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bản ghi thành công.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miêu tả yêu cầu nhập.
        /// </summary>
        internal static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hiển thị yêu cầu nhập.
        /// </summary>
        internal static string DisplayNameRequired {
            get {
                return ResourceManager.GetString("DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hiệu lực yêu cầu nhập.
        /// </summary>
        internal static string EffectDateRequired {
            get {
                return ResourceManager.GetString("EffectDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hòm thư yêu cầu nhập.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến dịch đã tồn tại.
        /// </summary>
        internal static string ERR_CAMPAIGN_EXISTED {
            get {
                return ResourceManager.GetString("ERR_CAMPAIGN_EXISTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiến dịch không xác định.
        /// </summary>
        internal static string ERR_CAMPAIGN_INVALID {
            get {
                return ResourceManager.GetString("ERR_CAMPAIGN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sự kiện yêu cầu nhập.
        /// </summary>
        internal static string EventDayRequired {
            get {
                return ResourceManager.GetString("EventDayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian sự kiện yêu cầu nhập.
        /// </summary>
        internal static string EventTimeRequired {
            get {
                return ResourceManager.GetString("EventTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ đổi thưởng không chính xác(thấp nhất 0.01).
        /// </summary>
        internal static string ExchangeRateMin {
            get {
                return ResourceManager.GetString("ExchangeRateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn yêu cầu nhập.
        /// </summary>
        internal static string ExpiredDateRequired {
            get {
                return ResourceManager.GetString("ExpiredDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link facebook yêu cầu nhập.
        /// </summary>
        internal static string FBLinkRequired {
            get {
                return ResourceManager.GetString("FBLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ yêu cầu nhập.
        /// </summary>
        internal static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ hết hiệu lực phải lớn hơn ngày giờ hiện tại.
        /// </summary>
        internal static string GiftCodeExpireDateMin {
            get {
                return ResourceManager.GetString("GiftCodeExpireDateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giftcode yêu cầu nhập.
        /// </summary>
        internal static string GiftCodeRequired {
            get {
                return ResourceManager.GetString("GiftCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại gift code yêu cầu nhập.
        /// </summary>
        internal static string GiftcodeTypeRequired {
            get {
                return ResourceManager.GetString("GiftcodeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        internal static string InsertSuccess {
            get {
                return ResourceManager.GetString("InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hũ sự kiện khởi tạo yêu cầu nhập.
        /// </summary>
        internal static string JackpotEventInitRequired {
            get {
                return ResourceManager.GetString("JackpotEventInitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hũ sự kiện yêu cầu nhập.
        /// </summary>
        internal static string JackpotEventQuotaRequired {
            get {
                return ResourceManager.GetString("JackpotEventQuotaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước nhảy yêu cầu nhập.
        /// </summary>
        internal static string JackpotStepJumpRequired {
            get {
                return ResourceManager.GetString("JackpotStepJumpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu nhỏ hơn thời gian kết thúc.
        /// </summary>
        internal static string LD_Event_EndTimeLessStartTime {
            get {
                return ResourceManager.GetString("LD_Event_EndTimeLessStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại cấu hình trong khoảng thời gian trên.
        /// </summary>
        internal static string LD_Event_ExistRecord {
            get {
                return ResourceManager.GetString("LD_Event_ExistRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải triệu hồi. Giá trị Min phải nhỏ hơn giá trị Max.
        /// </summary>
        internal static string LD_Event_PrizeMaxLessPrizeMin {
            get {
                return ResourceManager.GetString("LD_Event_PrizeMaxLessPrizeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể ghi log.
        /// </summary>
        internal static string LogCouldNotCreate {
            get {
                return ResourceManager.GetString("LogCouldNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ngày kết thúc.
        /// </summary>
        internal static string LuckySpin_EndDateRequired {
            get {
                return ResourceManager.GetString("LuckySpin_EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu và ngày kết thúc không được để trống.
        /// </summary>
        internal static string LuckySpin_ErrEmptyDate {
            get {
                return ResourceManager.GetString("LuckySpin_ErrEmptyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại cấu hình trong khoảng thời gian trên.
        /// </summary>
        internal static string LuckySpin_ErrExistConfigPresent {
            get {
                return ResourceManager.GetString("LuckySpin_ErrExistConfigPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượt quay phải lớn hơn 0.
        /// </summary>
        internal static string LuckySpin_ErrQuantity {
            get {
                return ResourceManager.GetString("LuckySpin_ErrQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lưu dữ liệu.
        /// </summary>
        internal static string LuckySpin_ErrSave {
            get {
                return ResourceManager.GetString("LuckySpin_ErrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu phải nhỏ hơn hoặc bằng ngày kết thúc.
        /// </summary>
        internal static string LuckySpin_ErrStartGreatEnd {
            get {
                return ResourceManager.GetString("LuckySpin_ErrStartGreatEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số lượt quay.
        /// </summary>
        internal static string LuckySpin_QuantityRequired {
            get {
                return ResourceManager.GetString("LuckySpin_QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập ngày bắt đầu.
        /// </summary>
        internal static string LuckySpin_StartDateRequired {
            get {
                return ResourceManager.GetString("LuckySpin_StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá tạo gift code yêu cầu nhập.
        /// </summary>
        internal static string MoneyRewardMoneyReward {
            get {
                return ResourceManager.GetString("MoneyRewardMoneyReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập lý do chuyển tiền.
        /// </summary>
        internal static string NoteRequired {
            get {
                return ResourceManager.GetString("NoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà mạng đã được sử dụng.
        /// </summary>
        internal static string OperatoerCodeExist {
            get {
                return ResourceManager.GetString("OperatoerCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà mạng yêu cầu nhập.
        /// </summary>
        internal static string OperatorCodeRequired {
            get {
                return ResourceManager.GetString("OperatorCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ đổi thưởng yêu cầu nhập.
        /// </summary>
        internal static string OperatorExChangeRateRequired {
            get {
                return ResourceManager.GetString("OperatorExChangeRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà mạng đã được sử dụng.
        /// </summary>
        internal static string OperatorNameExist {
            get {
                return ResourceManager.GetString("OperatorNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà mạng yêu cầu nhập.
        /// </summary>
        internal static string OperatorNameRequired {
            get {
                return ResourceManager.GetString("OperatorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ nạp thẻ không chính xác(thấp nhất 0.01).
        /// </summary>
        internal static string OperatorRateMin {
            get {
                return ResourceManager.GetString("OperatorRateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ nạp thẻ yêu cầu nhập.
        /// </summary>
        internal static string OperatorRateRequired {
            get {
                return ResourceManager.GetString("OperatorRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái yêu cầu nhập.
        /// </summary>
        internal static string OperatorStatusRequired {
            get {
                return ResourceManager.GetString("OperatorStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trị yêu cầu nhập.
        /// </summary>
        internal static string OrderNumRequired {
            get {
                return ResourceManager.GetString("OrderNumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số không hợp lệ.
        /// </summary>
        internal static string ParamaterInvalid {
            get {
                return ResourceManager.GetString("ParamaterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu yêu cầu nhập.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng thời gian cấu hình không hợp lệ.
        /// </summary>
        internal static string PeriodTimeOverlap {
            get {
                return ResourceManager.GetString("PeriodTimeOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại hiển thị yêu cầu nhập.
        /// </summary>
        internal static string PhoneDisplayRequired {
            get {
                return ResourceManager.GetString("PhoneDisplayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại yêu cầu nhập.
        /// </summary>
        internal static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá yêu cầu nhập.
        /// </summary>
        internal static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tối thiểu là 1.
        /// </summary>
        internal static string QuantityMin {
            get {
                return ResourceManager.GetString("QuantityMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng gift code yêu cầu nhập.
        /// </summary>
        internal static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người nhận yêu cầu nhập.
        /// </summary>
        internal static string RecevierUserNameRequired {
            get {
                return ResourceManager.GetString("RecevierUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật yêu cập nhập.
        /// </summary>
        internal static string SecretKeyRequired {
            get {
                return ResourceManager.GetString("SecretKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Mail thành công.
        /// </summary>
        internal static string SendMailSuccess {
            get {
                return ResourceManager.GetString("SendMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái yêu cầu nhập.
        /// </summary>
        internal static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống của chúng tôi đang bận .Xin quý khách vui lòng thử lại sau.
        /// </summary>
        internal static string SystemProccessing {
            get {
                return ResourceManager.GetString("SystemProccessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà mạng yêu cầu chọn.
        /// </summary>
        internal static string TelecomRequired {
            get {
                return ResourceManager.GetString("TelecomRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề yêu cầu nhập.
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển Bit thành công.
        /// </summary>
        internal static string TranferSuccess {
            get {
                return ResourceManager.GetString("TranferSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể khởi tạo giao dịch.
        /// </summary>
        internal static string TransasactionCouldNotCreate {
            get {
                return ResourceManager.GetString("TransasactionCouldNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        internal static string Updatesuccess {
            get {
                return ResourceManager.GetString("Updatesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập yêu cầu nhập.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại.
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng chưa được nhập.
        /// </summary>
        internal static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản Bit trong ví không đủ để giao dịch.
        /// </summary>
        internal static string WalletInvalid {
            get {
                return ResourceManager.GetString("WalletInvalid", resourceCulture);
            }
        }
    }
}
