//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsWebGame.SafeOtp.SendSmsServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://send_sms.vienthongdidong.vn/", ConfigurationName="SendSmsServices.send")]
    public interface send {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.sendResponse send(MsWebGame.SafeOtp.SendSmsServices.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendResponse> sendAsync(MsWebGame.SafeOtp.SendSmsServices.sendRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/getipRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/getipResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.getipResponse getip(MsWebGame.SafeOtp.SendSmsServices.getipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/getipRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/getipResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.getipResponse> getipAsync(MsWebGame.SafeOtp.SendSmsServices.getipRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQuestionRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQuestionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.sendQuestionResponse sendQuestion(MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQuestionRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQuestionResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQuestionResponse> sendQuestionAsync(MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/checkTransRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/checkTransResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.checkTransResponse checkTrans(MsWebGame.SafeOtp.SendSmsServices.checkTransRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/checkTransRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/checkTransResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.checkTransResponse> checkTransAsync(MsWebGame.SafeOtp.SendSmsServices.checkTransRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/QuestionRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/QuestionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.QuestionResponse Question(MsWebGame.SafeOtp.SendSmsServices.QuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/QuestionRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/QuestionResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.QuestionResponse> QuestionAsync(MsWebGame.SafeOtp.SendSmsServices.QuestionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/checkBalanceRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/checkBalanceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.checkBalanceResponse checkBalance(MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/checkBalanceRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/checkBalanceResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.checkBalanceResponse> checkBalanceAsync(MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendCskhRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendCskhResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.sendCskhResponse sendCskh(MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendCskhRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendCskhResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendCskhResponse> sendCskhAsync(MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQcRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQcResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.sendQcResponse sendQc(MsWebGame.SafeOtp.SendSmsServices.sendQcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQcRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQcResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQcResponse> sendQcAsync(MsWebGame.SafeOtp.SendSmsServices.sendQcRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQc2Request", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQc2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.sendQc2Response sendQc2(MsWebGame.SafeOtp.SendSmsServices.sendQc2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/sendQc2Request", ReplyAction="http://send_sms.vienthongdidong.vn/send/sendQc2Response")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQc2Response> sendQc2Async(MsWebGame.SafeOtp.SendSmsServices.sendQc2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/AdsSendRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/AdsSendResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MsWebGame.SafeOtp.SendSmsServices.AdsSendResponse AdsSend(MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://send_sms.vienthongdidong.vn/send/AdsSendRequest", ReplyAction="http://send_sms.vienthongdidong.vn/send/AdsSendResponse")]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.AdsSendResponse> AdsSendAsync(MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://send_sms.vienthongdidong.vn/")]
    public partial class sendsmsresponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string detailField;
        
        private string idTranField;
        
        private string receiptField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idTran {
            get {
                return this.idTranField;
            }
            set {
                this.idTranField = value;
                this.RaisePropertyChanged("idTran");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
                this.RaisePropertyChanged("receipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        public sendRequest() {
        }
        
        public sendRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return;
        
        public sendResponse() {
        }
        
        public sendResponse(MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getip", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class getipRequest {
        
        public getipRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getipResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class getipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getipResponse() {
        }
        
        public getipResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQuestion", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDQues;
        
        public sendQuestionRequest() {
        }
        
        public sendQuestionRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ, string IDQues) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
            this.IDQues = IDQues;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQuestionResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return;
        
        public sendQuestionResponse() {
        }
        
        public sendQuestionResponse(MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkTrans", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkTransRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        public checkTransRequest() {
        }
        
        public checkTransRequest(string transid, string USERNAME) {
            this.transid = transid;
            this.USERNAME = USERNAME;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkTransResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkTransResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return;
        
        public checkTransResponse() {
        }
        
        public checkTransResponse(MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Question", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class QuestionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QUESTION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANSWER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDCLIENT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANSCORRECT;
        
        public QuestionRequest() {
        }
        
        public QuestionRequest(string USERNAME, string QUESTION, string ANSWER, string IDCLIENT, string ANSCORRECT) {
            this.USERNAME = USERNAME;
            this.QUESTION = QUESTION;
            this.ANSWER = ANSWER;
            this.IDCLIENT = IDCLIENT;
            this.ANSCORRECT = ANSCORRECT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QuestionResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class QuestionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public QuestionResponse() {
        }
        
        public QuestionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkBalance", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public checkBalanceRequest() {
        }
        
        public checkBalanceRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkBalanceResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class checkBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkBalanceResponse() {
        }
        
        public checkBalanceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCskh", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendCskhRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        public sendCskhRequest() {
        }
        
        public sendCskhRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string PHONE, string IDREQ) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCskhResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendCskhResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return;
        
        public sendCskhResponse() {
        }
        
        public sendCskhResponse(MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQc", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        public sendQcRequest() {
        }
        
        public sendQcRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQcResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return;
        
        public sendQcResponse() {
        }
        
        public sendQcResponse(MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQc2", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQc2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("PHONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendtime;
        
        public sendQc2Request() {
        }
        
        public sendQc2Request(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ, string sendtime) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.TYPE = TYPE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
            this.sendtime = sendtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendQc2Response", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class sendQc2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return;
        
        public sendQc2Response() {
        }
        
        public sendQc2Response(MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdsSend", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class AdsSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USERNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASSWORD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRANDNAME;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PHONE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IDREQ;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendtime;
        
        public AdsSendRequest() {
        }
        
        public AdsSendRequest(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string[] PHONE, string IDREQ, string sendtime) {
            this.USERNAME = USERNAME;
            this.PASSWORD = PASSWORD;
            this.BRANDNAME = BRANDNAME;
            this.MESSAGE = MESSAGE;
            this.PHONE = PHONE;
            this.IDREQ = IDREQ;
            this.sendtime = sendtime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdsSendResponse", WrapperNamespace="http://send_sms.vienthongdidong.vn/", IsWrapped=true)]
    public partial class AdsSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://send_sms.vienthongdidong.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return;
        
        public AdsSendResponse() {
        }
        
        public AdsSendResponse(MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sendChannel : MsWebGame.SafeOtp.SendSmsServices.send, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sendClient : System.ServiceModel.ClientBase<MsWebGame.SafeOtp.SendSmsServices.send>, MsWebGame.SafeOtp.SendSmsServices.send {
        
        public sendClient() {
        }
        
        public sendClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sendClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sendClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sendClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.sendResponse MsWebGame.SafeOtp.SendSmsServices.send.send(MsWebGame.SafeOtp.SendSmsServices.sendRequest request) {
            return base.Channel.send(request);
        }
        
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse send(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ) {
            MsWebGame.SafeOtp.SendSmsServices.sendRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            MsWebGame.SafeOtp.SendSmsServices.sendResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).send(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendResponse> MsWebGame.SafeOtp.SendSmsServices.send.sendAsync(MsWebGame.SafeOtp.SendSmsServices.sendRequest request) {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendResponse> sendAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ) {
            MsWebGame.SafeOtp.SendSmsServices.sendRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.getipResponse MsWebGame.SafeOtp.SendSmsServices.send.getip(MsWebGame.SafeOtp.SendSmsServices.getipRequest request) {
            return base.Channel.getip(request);
        }
        
        public string getip() {
            MsWebGame.SafeOtp.SendSmsServices.getipRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.getipRequest();
            MsWebGame.SafeOtp.SendSmsServices.getipResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).getip(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.getipResponse> MsWebGame.SafeOtp.SendSmsServices.send.getipAsync(MsWebGame.SafeOtp.SendSmsServices.getipRequest request) {
            return base.Channel.getipAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.getipResponse> getipAsync() {
            MsWebGame.SafeOtp.SendSmsServices.getipRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.getipRequest();
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).getipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.sendQuestionResponse MsWebGame.SafeOtp.SendSmsServices.send.sendQuestion(MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest request) {
            return base.Channel.sendQuestion(request);
        }
        
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse sendQuestion(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ, string IDQues) {
            MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.IDQues = IDQues;
            MsWebGame.SafeOtp.SendSmsServices.sendQuestionResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendQuestion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQuestionResponse> MsWebGame.SafeOtp.SendSmsServices.send.sendQuestionAsync(MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest request) {
            return base.Channel.sendQuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQuestionResponse> sendQuestionAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string PHONE, string IDREQ, string IDQues) {
            MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendQuestionRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.IDQues = IDQues;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendQuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.checkTransResponse MsWebGame.SafeOtp.SendSmsServices.send.checkTrans(MsWebGame.SafeOtp.SendSmsServices.checkTransRequest request) {
            return base.Channel.checkTrans(request);
        }
        
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse checkTrans(string transid, string USERNAME) {
            MsWebGame.SafeOtp.SendSmsServices.checkTransRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.checkTransRequest();
            inValue.transid = transid;
            inValue.USERNAME = USERNAME;
            MsWebGame.SafeOtp.SendSmsServices.checkTransResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).checkTrans(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.checkTransResponse> MsWebGame.SafeOtp.SendSmsServices.send.checkTransAsync(MsWebGame.SafeOtp.SendSmsServices.checkTransRequest request) {
            return base.Channel.checkTransAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.checkTransResponse> checkTransAsync(string transid, string USERNAME) {
            MsWebGame.SafeOtp.SendSmsServices.checkTransRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.checkTransRequest();
            inValue.transid = transid;
            inValue.USERNAME = USERNAME;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).checkTransAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.QuestionResponse MsWebGame.SafeOtp.SendSmsServices.send.Question(MsWebGame.SafeOtp.SendSmsServices.QuestionRequest request) {
            return base.Channel.Question(request);
        }
        
        public string Question(string USERNAME, string QUESTION1, string ANSWER, string IDCLIENT, string ANSCORRECT) {
            MsWebGame.SafeOtp.SendSmsServices.QuestionRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.QuestionRequest();
            inValue.USERNAME = USERNAME;
            inValue.QUESTION = QUESTION1;
            inValue.ANSWER = ANSWER;
            inValue.IDCLIENT = IDCLIENT;
            inValue.ANSCORRECT = ANSCORRECT;
            MsWebGame.SafeOtp.SendSmsServices.QuestionResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).Question(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.QuestionResponse> MsWebGame.SafeOtp.SendSmsServices.send.QuestionAsync(MsWebGame.SafeOtp.SendSmsServices.QuestionRequest request) {
            return base.Channel.QuestionAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.QuestionResponse> QuestionAsync(string USERNAME, string QUESTION, string ANSWER, string IDCLIENT, string ANSCORRECT) {
            MsWebGame.SafeOtp.SendSmsServices.QuestionRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.QuestionRequest();
            inValue.USERNAME = USERNAME;
            inValue.QUESTION = QUESTION;
            inValue.ANSWER = ANSWER;
            inValue.IDCLIENT = IDCLIENT;
            inValue.ANSCORRECT = ANSCORRECT;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).QuestionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.checkBalanceResponse MsWebGame.SafeOtp.SendSmsServices.send.checkBalance(MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest request) {
            return base.Channel.checkBalance(request);
        }
        
        public string checkBalance(string username, string password) {
            MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest();
            inValue.username = username;
            inValue.password = password;
            MsWebGame.SafeOtp.SendSmsServices.checkBalanceResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).checkBalance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.checkBalanceResponse> MsWebGame.SafeOtp.SendSmsServices.send.checkBalanceAsync(MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest request) {
            return base.Channel.checkBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.checkBalanceResponse> checkBalanceAsync(string username, string password) {
            MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.checkBalanceRequest();
            inValue.username = username;
            inValue.password = password;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).checkBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.sendCskhResponse MsWebGame.SafeOtp.SendSmsServices.send.sendCskh(MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest request) {
            return base.Channel.sendCskh(request);
        }
        
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse sendCskh(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string PHONE, string IDREQ) {
            MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            MsWebGame.SafeOtp.SendSmsServices.sendCskhResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendCskh(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendCskhResponse> MsWebGame.SafeOtp.SendSmsServices.send.sendCskhAsync(MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest request) {
            return base.Channel.sendCskhAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendCskhResponse> sendCskhAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string PHONE, string IDREQ) {
            MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendCskhRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendCskhAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.sendQcResponse MsWebGame.SafeOtp.SendSmsServices.send.sendQc(MsWebGame.SafeOtp.SendSmsServices.sendQcRequest request) {
            return base.Channel.sendQc(request);
        }
        
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse sendQc(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ) {
            MsWebGame.SafeOtp.SendSmsServices.sendQcRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendQcRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            MsWebGame.SafeOtp.SendSmsServices.sendQcResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendQc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQcResponse> MsWebGame.SafeOtp.SendSmsServices.send.sendQcAsync(MsWebGame.SafeOtp.SendSmsServices.sendQcRequest request) {
            return base.Channel.sendQcAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQcResponse> sendQcAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ) {
            MsWebGame.SafeOtp.SendSmsServices.sendQcRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.sendQcRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendQcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.sendQc2Response MsWebGame.SafeOtp.SendSmsServices.send.sendQc2(MsWebGame.SafeOtp.SendSmsServices.sendQc2Request request) {
            return base.Channel.sendQc2(request);
        }
        
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse sendQc2(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ, string sendtime) {
            MsWebGame.SafeOtp.SendSmsServices.sendQc2Request inValue = new MsWebGame.SafeOtp.SendSmsServices.sendQc2Request();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.sendtime = sendtime;
            MsWebGame.SafeOtp.SendSmsServices.sendQc2Response retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendQc2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQc2Response> MsWebGame.SafeOtp.SendSmsServices.send.sendQc2Async(MsWebGame.SafeOtp.SendSmsServices.sendQc2Request request) {
            return base.Channel.sendQc2Async(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.sendQc2Response> sendQc2Async(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string TYPE, string[] PHONE, string IDREQ, string sendtime) {
            MsWebGame.SafeOtp.SendSmsServices.sendQc2Request inValue = new MsWebGame.SafeOtp.SendSmsServices.sendQc2Request();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.TYPE = TYPE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.sendtime = sendtime;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).sendQc2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MsWebGame.SafeOtp.SendSmsServices.AdsSendResponse MsWebGame.SafeOtp.SendSmsServices.send.AdsSend(MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest request) {
            return base.Channel.AdsSend(request);
        }
        
        public MsWebGame.SafeOtp.SendSmsServices.sendsmsresponse AdsSend(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string[] PHONE, string IDREQ, string sendtime) {
            MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.sendtime = sendtime;
            MsWebGame.SafeOtp.SendSmsServices.AdsSendResponse retVal = ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).AdsSend(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.AdsSendResponse> MsWebGame.SafeOtp.SendSmsServices.send.AdsSendAsync(MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest request) {
            return base.Channel.AdsSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<MsWebGame.SafeOtp.SendSmsServices.AdsSendResponse> AdsSendAsync(string USERNAME, string PASSWORD, string BRANDNAME, string MESSAGE, string[] PHONE, string IDREQ, string sendtime) {
            MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest inValue = new MsWebGame.SafeOtp.SendSmsServices.AdsSendRequest();
            inValue.USERNAME = USERNAME;
            inValue.PASSWORD = PASSWORD;
            inValue.BRANDNAME = BRANDNAME;
            inValue.MESSAGE = MESSAGE;
            inValue.PHONE = PHONE;
            inValue.IDREQ = IDREQ;
            inValue.sendtime = sendtime;
            return ((MsWebGame.SafeOtp.SendSmsServices.send)(this)).AdsSendAsync(inValue);
        }
    }
}
